apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-nginx
  labels:
    app: keda-nginx
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: keda-nginx
  template:
    metadata:
      labels:
        app: keda-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
